version: '3.7'
services:

  cloudflare-companion:
    image: tiredofit/traefik-cloudflare-companion
    container_name: cloudflare-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - TRAEFIK_VERSION=2
      - CF_EMAIL=email@example.com
      - CF_TOKEN=fbSx3dk"3.9"mJ6UukLQ7zRbo63H5UdsGSCqQnTvbJDgyQaTp

      - TARGET_DOMAIN=host.example.org
      - DOMAIN1=example.org
      - DOMAIN1_ZONE_ID=1234567890
      #- DOCKER_HOST=tcp://198.51.100.32:2376
      #- DOCKER_CERT_PATH=/docker-certs
      #- DOCKER_TLS_VERIFY=1
    networks:
    - internal
    - services
    restart: always

networks:
  internal:
    external: false
  services:
    external: true
