# See https://pre-commit.com for more information
# idee von k8s-at-home.com
# informed by oVerTopp from discord
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.0.1
  hooks:
  - id: check-executables-have-shebangs
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: mixed-line-ending
  - id: check-merge-conflict
  - id: check-case-conflict
