#!/usr/bin/env bash

ARCH="$(command arch)"
if [ "${ARCH}" = "x86_64" ]; then
     ARCH="amd64"
elif [ "${ARCH}" = "aarch64" ]; then
     ARCH="arm64"
elif [ "${ARCH}" = "armv7l" ]; then
     ARCH="armhf"
else
     echo "**** Unsupported Linux architecture ${ARCH} found, exiting... ****"
     exit 1
fi

VERSION=$(curl -sX GET "https://api.github.com/repos/rclone/rclone/releases/latest" | awk '/tag_name/{print $4;exit}' FS='[""]' | sed -e 's_^v__')
curl -o /tmp/rclone.zip -SL https://github.com/rclone/rclone/releases/download/v${VERSION}/rclone-v${VERSION}-linux-${ARCH}.zip
cd /tmp/ && unzip -q /tmp/rclone.zip
mv /tmp/rclone-*-linux-${ARCH}/rclone /usr/local/bin/
rm -rf /var/cache/apk/* /tmp/*

#<EOF>#
