#!/command/with-contenv bash
# shellcheck shell=bash
####################################
# Docker owned by homelabarr       #
# Docker Maintainer smashingtags   #
####################################

function log() {
   GRAY="\033[0;37m"
   BLUE="\033[0;34m"
   NC="\033[0m"
   $(which echo) -e "${GRAY}[$(date +'%Y/%m/%d %H:%M:%S')]${BLUE} [Mount]${NC} ${1}"
}
umask 022

source /system/mount/mount.env
source /app/mount/function.sh && lang

if [[ "${NZBCLEANUP}" != "false" ]]; then
  log "${startupnzb}" && nzbcleanup
else
  $(which sleep) infinity
fi
