#!/usr/bin/with-contenv bash

# Set user and group IDs
PUID=${PUID:-1000}
PGID=${PGID:-1000}

# Update abc user uid and gid
groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc

echo "
-------------------------------------
HomelabARR Container - Ubuntu Noble
-------------------------------------
GID/UID
-------------------------------------
User uid:    $(id -u abc)
User gid:    $(id -g abc)
-------------------------------------
"

# Set ownership
chown abc:abc /app
chown abc:abc /config
chown abc:abc /defaults
[ -d /data ] && chown abc:abc /data