#!/command/with-contenv bash
# shellcheck shell=bash
####################################
# Docker owned by homelabarr       #
# Docker Maintainer smashingtags   #
####################################
function log() {
   GRAY="\033[0;37m"
   BLUE="\033[0;34m"
   NC="\033[0m"
   $(which echo) -e "${GRAY}[$($(which date) +'%Y/%m/%d %H:%M:%S')]${BLUE} [Uploader]${NC} ${1}"
}

source /app/uploader/function.sh && lang

log "${startupcaddy}"

exec s6-setuidgid abc /usr/sbin/caddy run --config /conf/Caddyfile &>/dev/null
