#!/usr/bin/with-contenv bash

PUID=${PUID:-911}
PGID=${PGID:-911}
if [ ! "$(id -u abc)" -eq "$PUID" ]; then usermod -o -u "$PUID" abc; fi
if [ ! "$(id -g abc)" -eq "$PGID" ]; then groupmod -o -g "$PGID" abc; fi


echo "----------------------------------------------------

 ____             _                                 
|  _ \  ___   ___| | _____  ___ _ ____   _____ _ __ 
| | | |/ _ \ / __| |/ / __|/ _ \ '__\ \ / / _ \ '__|
| |_| | (_) | (__|   <\__ \  __/ |   \ V /  __/ |   
|____/ \___/ \___|_|\_\___/\___|_|    \_/ \___|_|

----------------------------------------------------"


chown abc:abc /app \
              /config \
              /defaults
