#!/command/with-contenv bash
# shellcheck shell=bash
####################################
# Docker owned by homelabarr       #
# Docker Maintainer smashingtags   #
####################################

/usr/sbin/crond -m off -p -s -n
