#!/command/with-contenv bash
# shellcheck shell=bash
#####################################
# All rights reserved.              #
# started from Zero                 #
# Docker owned dockserver           #
# Docker Maintainer dockserver      #
#####################################
#####################################
# THIS DOCKER IS UNDER LICENSE      #
# NO CUSTOMIZING IS ALLOWED         #
# NO REBRANDING IS ALLOWED          #
# NO CODE MIRRORING IS ALLOWED      #
#####################################
function log() {
     echo "${1}"
}

addgroup -S abc
adduser -S abc -G abc
PGID=${PGID:-1000}
PUID=${PUID:-1000}
groupmod -o -g "$PGID" abc
usermod -o -u "$PUID" abc

if [[ -f /donate.txt ]]; then cat /donate.txt ; fi
echo '
-------------------------------------
GID/UID
-------------------------------------'
echo "
User uid:    $(id -u abc)
User gid:    $(id -g abc)
-------------------------------------
"
   cat > /etc/apk/repositories << EOF; $(echo)
http://dl-cdn.alpinelinux.org/alpine/v$(cat /etc/alpine-release | cut -d'.' -f1,2)/main
http://dl-cdn.alpinelinux.org/alpine/v$(cat /etc/alpine-release | cut -d'.' -f1,2)/community
http://dl-cdn.alpinelinux.org/alpine/edge/testing
EOF

   apk --quiet --no-progress update && \
   apk --quiet --no-progress upgrade && \
   apk --quiet --no-progress add git

   if [[ "${GIT_REPO}" != "" ]]; then
      mkdir -p /opt/appdata/compose
      git -C /tmp/apps clone "${GIT_REPO}"
      find /opt/appdata/compose -type f -name "*.yml' -delete
      find /opt/appdata/compose -type f -name "*.yaml' -delete
      find /opt/appdata/compose -type f -name "*.png' -delete
      find /opt/appdata/compose -type f -name "*.md' -delete
      find /opt/appdata/compose -type d -empty -delete
      cp -r /tmp/apps /opt/appdata/compose
      rm -rf /tmp/apps
   fi

echo "------------------------------
    _____   _   _  __  __
   |_   _| | | | | \ \/ /
     | |   | |_| |  \  / 
     | |   |  _  |  /  \ 
     |_|   |_| |_| /_/\_\

------------------------------
     to all the coders

We have take some code from :

  88lex , RTRO , edrock200
 ChaoticWeg & linuxserver.io

       and all other
  If we missed you, sorry..

------------------------------"
