#!/usr/bin/with-contenv bash

APP="$(basename -- $(for i in $(ls -d /config/*/); do echo ${i%%/}; done))"
if [[ -d "/mnt/unionfs" ]]; then
   while [ -z "`ls /mnt/unionfs`" ]
   do
      echo "wait mount /mnt/unionfs" && sleep 10
   done
   echo "mount working! $APP starting..."
fi

# env settings
APP_DIR="/app/emby"
export LD_LIBRARY_PATH="${APP_DIR}"
export FONTCONFIG_PATH="${APP_DIR}"/etc/fonts
if [ -d "/lib/x86_64-linux-gnu" ]; then
   export LIBVA_DRIVERS_PATH=/usr/lib/x86_64-linux-gnu/dri:"${APP_DIR}"/dri
fi
export SSL_CERT_FILE="${APP_DIR}"/etc/ssl/certs/ca-certificates.crt

exec \
   s6-setuidgid abc /app/emby/EmbyServer \
   -programdata /config \
   -ffdetect /app/emby/ffdetect \
   -ffmpeg /app/emby/ffmpeg \
   -ffprobe /app/emby/ffprobe \
   -restartexitcode 3 >/dev/null 2>&1
