#!/usr/bin/with-contenv bash
# shellcheck shell=bash
#####################################
# All rights reserved.              #
# started from Zero                 #
# Docker owned dockserver           #
# Docker Maintainer dockserver      #
#####################################
# THIS DOCKER IS UNDER LICENSE      #
# NO CUSTOMIZING IS ALLOWED         #
# NO REBRANDING IS ALLOWED          #
# NO CODE MIRRORING IS ALLOWED      #
#####################################

APP="${HOSTNAME^}"

function log() {
   GRAY="\033[0;37m"
   BLUE="\033[0;34m"
   NC="\033[0m"
   $(which echo) -e "${GRAY}[$($(which date) +'%Y/%m/%d %H:%M:%S')]${BLUE} [${APP}]${NC} ${1}"
}

mkdir -p \
    /mnt/unionfs/torrents \
    /mnt/unionfs/torrents/incomplete \
    /mnt/unionfs/torrents/watch \
    /mnt/unionfs/torrents/backup

lsiown abc:abc \
    /mnt/unionfs/torrents \
    /mnt/unionfs/torrents/incomplete \
    /mnt/unionfs/torrents/watch \
    /mnt/unionfs/torrents/backup

# copy config
[[ ! -e /config/qBittorrent/qBittorrent.conf ]] && \
    cp /defaults/qBittorrent.conf /config/qBittorrent/qBittorrent.conf

# chown download directory if currently not set to abc
if [[ -d /mnt/unionfs/torrents ]]; then
    if [[ "$(stat -c '%U' /mnt/unionfs/torrents)" != "abc" ]]; then
        chown -R abc:abc /mnt/unionfs/torrents
    fi
fi