#!/command/with-contenv bash
####################################
# Docker owned by homelabarr       #
# Docker Maintainer smashingtags   #
####################################

bash /app/cron/cron.sh root

/usr/sbin/crond -f -S -l 0 -c /etc/crontabs
