#!/usr/bin/with-contenv bash
# shellcheck shell=bash
####################################
# Docker owned by homelabarr       #
# Docker Maintainer smashingtags   #
####################################

#### INSTALL PACKAGES
apk add --quiet -no-progress --update wget

#### INSTALL RCLONE
$(which wget) -qO- https://rclone.org/install.sh | bash &>/dev/null
