##################################
#     Authelia configuration     #
##################################

theme: auto
jwt_secret: ${JWTTOKEN}

default_redirection_url: https://authelia.${DOMAINNAME}

server:
  host: 0.0.0.0
  port: 9091
  read_buffer_size: 4096
  write_buffer_size: 4096
  enable_pprof: false
  enable_expvars: false
  disable_healthcheck: false
  asset_path: "'/config/assets/'"

log:
  level: info
  format: text
  file_path: "'/config/authelia.log'"
  keep_stdout: false

totp:
  issuer: ${DOMAINNAME}
  period: 30
  skew: 1

#duo_api:
#  hostname: duo_api.${DOMAINNAME}
#  integration_key: here-the-key
#  secret_key: here-the-secret-key

authentication_backend:
  password_reset:
    ## Disable both the HTML element and the API for reset password functionality.
    disable: false
  refresh_interval: 5m
  file:
    path: "'/config/users_database.yml'"
    password:
      algorithm: argon2id
      iterations: 4
      key_length: 32
      salt_length: 32
      parallelism: 8
      memory: 1024

# Rules applied to everyone
access_control:
  default_policy: deny
  rules:
    # bypass rule for login
    - domain: authelia.${DOMAINNAME}
      policy: bypass
    # bypass rules for api / trigges / rss / xmltv
    - domain: "'*.${DOMAINNAME}'"
      policy: bypass
      resources:
        - "'^/api([/?].*)?$'"
        - "'^/identity.*$'"
        - "'^/triggers.*$'"
        - "'^/rss/*$'"
        - "'^/xmltv/*$'"
        - "'^/liverel.*$'"
        - "'^/meshagents.*$'"
        - "'^/meshsettings.*$'"
        - "'^/agent.*$'"
        - "'^/control.*$'"
        - "'^/meshrelay.*$'"
        - "'^/wl/.*$"'
    ## bypass rule for Uptime-Kuma (Status Page)
    - domain: "'uptime-kuma.{DOMAINNAME}'"
      policy: bypass
      resources:
        - "'^/status?.*$'"
        - "'^/assets/.*$'"
        - "'^/upload/logo.png.*$'"
        - "'^/icon.svg'"
    ## block admin bitwarden resources
    - domain: "'bitwarden.${DOMAINNAME}'"
      policy: one_factor
      resources:
        - "'^*/admin.*$'"
    ## one factor login
    - domain: "'*.${DOMAINNAME}'"
      policy: one_factor
    ## deny rule
    - domain: "'${DOMAIN}'"
      policy: deny
    - domain: ${SERVERIPID}
      policy: deny

session:
  name: authelia_session
  secret: ${SECTOKEN}
  same_site: lax
  expiration: 1h
  inactivity: 10m
  remember_me_duration: 1M
  domain: example.com

regulation:
  max_retries: 3
  find_time: 10m
  ban_time: 12h

storage:
  encryption_key: ${ENCTOKEN}
  local:
    path: /config/db.sqlite3

notifier:
  disable_startup_check: false
  filesystem:
    filename: /config/notification.txt

ntp:
  address: "'time.cloudflare.com:123'"
  version: 3
  max_desync: 3s
  disable_startup_check: false
  disable_failure: false

##################################
#     Authelia configuration     #
##################################
