version: '3.3'
services:
  newznab-docker:
    container_name: newznab
    image: ghcr.io/dockserver/docker-newznab
    restart: "${RESTARTAPP}"
    networks:
      - ${DOCKERNETWORK}
    security_opt:
      - "${SECURITYOPS}:${SECURITYOPSSET}"
    volumes:
      - "${APPFOLDER}/newz/covers:/var/www/newznab/www/covers"
      - "${APPFOLDER}/newz/nzbs:/var/www/newznab/nzbfiles"
      - "unionfs:/mnt"
    environment:
      - "PGID=${ID}"
      - "PUID=${ID}"
      - "TZ=${TZ}"
      - "UMASK=${UMASK}"
      - "NNUSER=doob"
      - "NNPASS=mia2608alina"
      - "DB_TYPE=mysql"
      - "DB_HOST=localhost"
      - "DB_PORT=3306"
      - "DB_USER=newznab"
      - "DB_PASSWORD=newznabpassword"
      - "DB_NAME=newznab"
      - "NNTP_USERNAME=mrdoob"
      - "NNTP_PASSWORD=Mia2608AlinA"
      - "NNTP_SERVER=news.eweka.nl"
      - "NNTP_PORT=569"
      - "NNTP_SSLENABLED=true"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "dockupdater.enable=true"
      - "traefik.http.routers.nzb-rtr.entrypoints=https"
      - "traefik.http.routers.nzb-rtr.rule=Host(`indexer.${DOMAIN}`)"
      - "traefik.http.routers.nzb-rtr.tls=true"
      - "traefik.http.routers-nzb-rtr.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.nzb-rtr.middlewares=chain-authelia@file"
      - "traefik.http.routers.nzb-rtr.service=radarr-svc"
      - "traefik.http.services.nzb-svc.loadbalancer.server.port=80"
networks:
  proxy:
    driver: bridge
    external: true
volumes:
  unionfs:
    driver: local-persist
    driver_opts:
      mountpoint: /mnt
