#!/usr/bin/with-contenv bash
# shellcheck shell=bash
####################################
# Docker owned by homelabarr       #
# Docker Maintainer smashingtags   #
####################################
umask 022

chown -cR abc:abc /app /system/* &>/dev/null
chmod -cR 755 /app /system/* &>/dev/null

exec s6-setuidgid abc /timer/remove.sh

#EOF#
