#!/command/with-contenv bash
# shellcheck shell=bash
####################################
# Docker owned by homelabarr       #
# Docker Maintainer smashingtags   #
####################################

function log() {
   GRAY="\033[0;37m"
   BLUE="\033[0;34m"
   NC="\033[0m"
   $(which echo) -e "${GRAY}[$(date +'%Y/%m/%d %H:%M:%S')]${BLUE} [Mount]${NC} ${1}"
}
umask 022

source /app/mount/function.sh && lang

MSG="${startupmount}" && notification
$(which sleep) 1
$(which logrotate) /etc/logrotate.conf &>/dev/null
rcmount && log "${startuprclone}" || { log "${failedrclone}"; exit 1; }
$(which sleep) 10
rcmergerfs && log "${startupmergerfs}" || { log "${failedmergerfs}"; exit 1; }
testsuccessfull && $(which sleep) 360

testrun
