#!/usr/bin/with-contenv bash
# shellcheck shell=bash

while true; do
   if mountpoint -q "/mnt/unionfs"; then
      break
   else
     sleep 5
   fi
done

cd /app/prowlarr/bin || exit

exec \
  s6-setuidgid abc \
  /app/prowlarr/bin/Prowlarr \
  -nobrowser -data=/config >/dev/null 2>&1
