q: 0
nServer: 1
mp4mux: false
timeout: 5000
partsize: 5
fsRetryTime: 10
mp4: true
noCleanUp: false
skipUpdate: true
forceMuxer: ffmpeg
fileName: "{showTitle}/{showTitle}.{title}.S{season}E{episode}.{height}p.WEBHD.AAC.H264-{relgroup}"
relgroup: DOCKSERVER
numbers: 1
