#!/usr/bin/with-contenv bash
# shellcheck shell=bash

function log() {
   GRAY="\033[0;37m"
   BLUE="\033[0;34m"
   NC="\033[0m"
   $(which echo) -e "${GRAY}[$($(which date) +'%Y/%m/%d %H:%M:%S')]${BLUE} [Radarr]${NC} ${1}"
}

log "-> Checking Mount"

APP="${HOSTNAME}"
if [[ -d "/mnt/unionfs" ]]; then
   while [ -z "`ls /mnt/unionfs`" ]
   do
      log "-> Wait Mount /mnt/unionfs" && sleep 10
   done
   log "-> Mount working! ${APP} starting"
   log "-> Starting ${APP}"
fi
