#!/usr/bin/with-contenv bash

while true; do
   if mountpoint -q "/mnt/unionfs"; then
      break
   else
     sleep 5
   fi
done

exec \
    s6-setuidgid abc /app/readarr/bin/Readarr \
    -nobrowser -data=/config >/dev/null 2>&1
