#!/usr/bin/with-contenv bash

addgroup -S abc &>/dev/null
adduser -S abc -G abc &>/dev/null
PGID=${PGID:-1000}
PUID=${PUID:-1000}
groupmod -o -g "$PGID" abc &>/dev/null
usermod -o -u "$PUID" abc &>/dev/null

if [[ -f /donate.txt ]]; then
   $(which cat) /donate.txt
fi

$(which echo) '
-------------------------------------
GID/UID
-------------------------------------'
echo "
User uid:    $(id -u abc)
User gid:    $(id -g abc)
-------------------------------------
"

# permissions
chown -R abc:abc \
	/app \
	/config

