#!/usr/bin/bash

if [ -z `command -v git` ]; then
   echo "**** installing git ****" && \
   apk --no-cache add git
fi

SCRIPTS_DIR=/app/tautulli/scripts
SCRIPTS_LINK=https://github.com/blacktwin/JBOPS

if [[ ! -d "${SCRIPTS_DIR}/.git" ]]; then
   echo "**** no scripts found, cloning. ****" && \
   git clone --depth 1 ${SCRIPTS_LINK} ${SCRIPTS_DIR} &> /dev/null
   pip3 install --no-cache-dir -U ${SCRIPTS_DIR}/requirements.txt
else
   echo "**** scripts found, pulling latest. ****" && \
   git -C ${SCRIPTS_DIR} pull &> /dev/null
   pip3 install --no-cache-dir -U ${SCRIPTS_DIR}/requirements.txt
fi

SCRIPTS_DIR=/app/tautulli/scripts
DIR_OWNER=`stat -c "%U:%G" ${SCRIPTS_DIR}`
if [[ ${DIR_OWNER} != "abc:abc" ]]; then
    echo "chowning ${SCRIPTS_DIR} please be patient" && \
    chown -R abc:abc ${SCRIPTS_DIR} &> /dev/null
fi

chmod -R +x ${SCRIPTS_DIR}/*/*.py &> /dev/null
CHOWN_DIR=/config
DIR_OWNER=`stat -c "%U:%G" $CHOWN_DIR`

if [[ ${DIR_OWNER} != "abc:abc" ]]; then
    echo "chowning ${CHOWN_DIR} please be patient" && \
    chown -R abc:abc ${CHOWN_DIR} &> /dev/null
fi
