#!/bin/bash
####################################
# All rights reserved.              #
# started from Zero                 #
# Docker owned dockserver           #
# Docker Maintainer dockserver      #
#####################################
#####################################
# THIS DOCKER IS UNDER LICENSE      #
# NO CUSTOMIZING IS ALLOWED         #
# NO REBRANDING IS ALLOWED          #
# NO CODE MIRRORING IS ALLOWED      #
#####################################
# shellcheck disable=SC2086
# shellcheck disable=SC2046

FOLDER=$1
APP=$2
USERNAME=$3
TOKEN=$4

### APP SETTINGS ###

APPBRANCH="master"
APPLINK="https://api.github.com/mregni/EmbyStat"

## FOR DOCKER RELEASE NUMBER
NEWVERSION="$(curl -u $USERNAME:$TOKEN -sX GET "https://api.github.com/repos/mregni/EmbyStat/releases" | jq -r 'first(.[] | .tag_name)')"
NEWVERSION="${NEWVERSION#*v}"
NEWVERSION="${NEWVERSION#*release-}"
NEWVERSION="${NEWVERSION}"

DESCRIPTION="$(curl -u $USERNAME:$TOKEN -sX GET "$APPLINK" | jq -r '.description')"
HEADLINE="$(cat ./.templates/headline.txt)"
BASEIMAGE="ghcr.io/linuxserver/baseimage-ubuntu:focal"

UPTCOMMAND="apt-get update -yqq"
INSTCOMMAND="apt-get install -yqq"
PACKAGES="jq libicu66 libssl1.0 unzip curl"
APPSPEC="chmod +x /opt/embystat/EmbyStat"
CLEANUP="rm -rf /tmp/* /var/lib/apt/lists/* /var/tmp/*"

PICTURE="./images/$APP.png"
APPFOLDER="./$FOLDER/$APP"
PORT="EXPOSE 6555"
VOLUMEN="VOLUME /config"

### RELEASE SETTINGS ###

echo '{
   "appname": "'${APP}'",
   "apppic": "'${PICTURE}'",
   "appfolder": "./'$FOLDER'/'$APP'",
   "newversion": "'${NEWVERSION}'",
   "appbranch": "'${APPBRANCH}'",
   "baseimage": "'${BASEIMAGE}'",
   "description": "'${DESCRIPTION}'",
   "body": "Upgrading '${APP}' to '${NEWVERSION}'",
   "user": "github-actions[bot]"
}' > "./$FOLDER/$APP/release.json"

### DOCKER BUILD ###
### GENERATE Dockerfile based on release.json

echo '## This file is automatically generated (based on release.json)
##
## Do not changes any lines here
##
'"${HEADLINE}"'
FROM '"${BASEIMAGE}"'
LABEL org.opencontainers.image.source="'"https://github.com/dockserver/container"'"

ARG TARGETPLATFORM
ARG BUILDPLATFORM

ARG VERSION="'"${NEWVERSION}"'"
ARG BRANCH="'"${APPBRANCH}"'"

ENV HOME="'"/config"'"

RUN  \
  echo "'"**** update system ****"'" && \
    '"${UPTCOMMAND}"' && \
  echo "'"**** install packages ****"'" && \
    '"${INSTCOMMAND}"' '"${PACKAGES}"' && \
  echo "'"**** install '"${APP}"' ****"'" && \
    mkdir -p /opt/embystat && \
    curl -o /tmp/embystat.zip -L "'"https://github.com/mregni/EmbyStat/releases/download/"'${VERSION}'"/EmbyStat-ubuntu-x64-v"'${VERSION}'".zip"'" && \
    unzip -q /tmp/embystat.zip -d /opt/embystat/ 2> /dev/null || true && \
    '"${APPSPEC}"' && \        
  echo "'"**** cleanup ****"'" && \
    '"${CLEANUP}"'

COPY '"${APPFOLDER}"'/root/ /

'"${PORT}"'
'"${VOLUMEN}"'
##EOF' > ./$FOLDER/$APP/Dockerfile
