#!/bin/bash
####################################
# All rights reserved.              #
# started from Zero                 #
# Docker owned dockserver           #
# Docker Maintainer dockserver      #
#####################################
#####################################
# THIS DOCKER IS UNDER LICENSE      #
# NO CUSTOMIZING IS ALLOWED         #
# NO REBRANDING IS ALLOWED          #
# NO CODE MIRRORING IS ALLOWED      #
#####################################
# shellcheck disable=SC2086
# shellcheck disable=SC2046

FOLDER=$1
APP=$2
USERNAME=$3
TOKEN=$4

### APP SETTINGS ###
APPLINK="https://api.github.com/repos/dockserver/dockserver"
BUILDVERSION=$(curl -sX GET "https://registry.hub.docker.com/v2/repositories/library/alpine/tags" \
   | jq -r 'select(.results != null) | .results[]["name"]' \
   | sort -t "." -k1,1n -k2,2n -k3,3n | grep "\." | tail -n1)
BUILDVERSION="${BUILDVERSION#*v}"
BUILDVERSION="${BUILDVERSION#*release-}"
BUILDVERSION="${BUILDVERSION}"

BUILDIMAGE="alpine"
ALPINEVERSION="${BUILDVERSION}"

HEADLINE="$(cat ./.templates/headline.txt)"
ADDS6="$(cat ./.templates/ci/s6-overlay)"

PICTURE="./images/$APP.png"
APPFOLDER="./$FOLDER/$APP"

## S6-OVERLAY
S6_STAGE_VERSION="$(curl -u $USERNAME:$TOKEN -sX GET "https://api.github.com/repos/just-containers/s6-overlay/releases/latest" | jq --raw-output '.tag_name')"

## RELEASE SETTINGS ###

echo '{
   "appname": "'${APP}'",
   "apppic": "'${PICTURE}'",
   "appfolder": "./'$FOLDER'/'$APP'",
   "newversion": "'${BUILDVERSION}'",
   "baseimage": "'${BUILDIMAGE}'",
   "baseversion": "'${ALPINEVERSION}'",
   "s6stage": "'${S6_STAGE_VERSION}'",
   "description": "Docker '${APP}' with include s6-overlay: '${S6_STAGE_VERSION}'",
   "body": "Upgrading '${APP}' to baseimage: '${BUILDIMAGE}':'${BUILDVERSION}'  with include s6-overlay: '${S6_STAGE_VERSION}'",
   "user": "dockserver image update[bot]"
}' > "./$FOLDER/$APP/release.json"

### DOCKER BUILD ###
### GENERATE Dockerfile based on release.json

echo '## This file is automatically generated (based on release.json)
##
## Do not changes any lines here
##
'"${HEADLINE}"'
FROM '"${BUILDIMAGE}"':'"${BUILDVERSION}"'
LABEL org.opencontainers.image.source="'"https://github.com/dockserver/container"'"

### BUILD STAGE
ARG TARGETPLATFORM
ARG BUILDPLATFORM

'"${ADDS6}"'

ENTRYPOINT [ "'"/init"'" ]
##EOF' > ./$FOLDER/$APP/Dockerfile
