#!/usr/bin/with-contenv bash

# make our folders
   mkdir -p /mnt/unionfs/nzb \
      /mnt/unionfs/nzb/incomplete \
      /mnt/unionfs/nzb/watch \
      /mnt/unionfs/nzb/backup

# check if config file exists in /config
[[ ! -f /config/nzbget.conf ]] && \
    cp /app/nzbget/share/nzbget/nzbget.conf /config/nzbget.conf

## NEDD PART TO CHANGE OR INJECTION THE EDITS
[[ -f /config/nzbget.conf ]] && \
     printf "Change Values ... "
     dlfolder="/mnt/unionfs/nzb/"
     infolder="/mnt/unionfs/nzb/incomplete"
     wtnzb="/mnt/unionfs/nzb/backup"
     wtn2="/mnt/unionfs/nzb/watch"

     sed -i -e "s/^DestDir\s*=.*$/DestDir=${dlfolder}/g" /config/nzbget.conf
     sed -i -e "s/^InterDir\s*=.*$/InterDir=${infolder}/g" /config/nzbget.conf
     sed -i -e "s/^NzbDir\s*=.*$/NzbDir=${wtnzb}/g" /config/nzbget.conf
     sed -i -e "s/^MainDir\s*=.*$/MainDir=/config/g" /config/nzbget.conf
     sed -i -e "s/^ScriptDir\s*=.*$/ScriptDir=${MainDir}/scripts/g" /config/nzbget.conf
     sed -i -e "s/^ControlUsername\s*=.*$/ControlUsername=/g" /config/nzbget.conf
     sed -i -e "s/^ControlPassword\s*=.*$/ControlPassword=/g" /config/nzbget.conf
     sed -i -e "s/^DirectUnpack\s*=.*$/DirectUnpack=yes/g" /config/nzbget.conf
     sed -i -e "s/^HealthCheck\s*=.*$/HealthCheck=Delete/g" /config/nzbget.conf
     sed -i -e "s/^DiskSpace\s*=.*$/DiskSpace=25000/g" /config/nzbget.conf

# permissions
chown abc:abc \
    /mnt/unionfs/nzb \
    /mnt/unionfs/nzb/incomplete \
    /mnt/unionfs/nzb/watch \
    /mnt/unionfs/nzb/backup

chown abc:abc -R \
    /app/nzbget \
    /config

chmod u+rw \
    /config/nzbget.conf
