#!/usr/bin/with-contenv bash
# shellcheck shell=bash
#####################################
# All rights reserved.              #
# started from Zero                 #
# Docker owned dockserver           #
# Docker Maintainer dockserver      #
#####################################
#####################################
# THIS DOCKER IS UNDER LICENSE      #
# NO CUSTOMIZING IS ALLOWED         #
# NO REBRANDING IS ALLOWED          #
# NO CODE MIRRORING IS ALLOWED      #
#####################################
function log() {
echo "[GUI] ${1}"
}

log "**** update system ****"
  apk --quiet --no-cache --no-progress update
  apk --quiet --no-cache --no-progress upgrade
  apk --quiet --no-cache --no-progress fix

log "**** install build packages ****" 

apk add --quiet --no-cache --no-progress \ 
    unzip \
    tar \
    pigz \
    tree \
    shadow \
    tzdata \
    faenza-icon-theme \
    faenza-icon-theme-xfce4-appfinder \
    faenza-icon-theme-xfce4-panel \
    mousepad \
    thunar \
    xfce4 \
    xfce4-terminal && \
  apk add --no-cache --repository=http://dl-cdn.alpinelinux.org/alpine/edge/testing \ 
    xfce4-pulseaudio-plugin && \
  echo "**** cleanup ****" && \
    rm -rf /tmp/* && \
    rm -rf /var/cache/apk/*

#"#
