#!/usr/bin/with-contenv bash

[[ -e /config/$MAP.pid ]] && \
    rm -rf /config/$MAP.pid

# install packages if needed
[[ -e `command -v apk` ]] && \
    echo "**** installing packages ****" && \
    apk add --no-cache ffmpeg curl wget git

[[ -e `command -v apt` ]] && \
    echo "**** installing packages ****" && \
    apt-get install --no-install-recommends -y ffmpeg curl wget git

######

[[ -d "/config/scripts" ]] && \
   rm -rf /config/scripts

[[ ! -d "/config/scripts" ]] && \
   mkdir /config/scripts && \
   git clone --quiet --depth 1  https://github.com/clinton-hall/nzbToMedia.git /config/scripts/ && \
   rm -rf /config/scripts/.gi*

chown -R abc:abc "/config/scripts" &>/dev/null
chown -R abc:abc "/timer/"
chmod 755 /timer/*

for i in `ls /config/scripts/`; do
    chmod a+x /config/scripts/$i &>/dev/null
done
